save_snapshot: false
load_snap: ''
replay_buffer_num_workers: 10
nstep: 3
batch_size: 16
train_steps: 2000000
eval_freq: 20000
num_same: 1
seed: 1
device: cuda
save_video: true
save_train_video: false
experiment: rep_0217_size
lr: 0.0001
lowdim: 0
alpha: 0.2
dataset: ego4d
wandbproject: drq_rep
simclr: false
doaug: rctraj
agent:
  _target_: robolang_rep.R3M
  device: ${device}
  lr: ${lr}
  hidden_dim: 1024
  finetune: 1
  pretrained: 0
  size: 18
  l2weight: 1.0e-05
  l1weight: 1.0e-05
  anneall1: false
  tcnweight: 1.0
  langweight: 1.0
  structured: true
  lang_cond: false
  l2dist: true
  attntype: modulate
  finetunelang: 0
  num_same: ${num_same}
  langtype: lorel
  mask: false
  simclr: ${simclr}
  bs: ${batch_size}
